config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root '/en', controller: 'users', action: 'guest'
  scope ':locale', locale: /en|ru/ do
    devise_for :users, locale: I18n.locale

    resources :clients, only: %i[index show] do
      resources :orders
    end

    resources :users, only: %i[edit update destroy guest]

    get '/no_orders', to: 'users#no_orders'
    get '/show_mechanics', to: 'users#show_mechanics'
    get '/show_teammates', to: 'users#show_teammates'
    get '/forget_password', to: 'users#forget_password'
    get '/send_reset_password_instructions', to: 'users#send_reset_password_instructions'

    get '/guest', to: 'clients#guest'
    get '/me', to: 'clients#me'

    get '/show_services', to: 'orders#show_services'
    get '/show_actual_orders', to: 'orders#show_actual_orders'

    get '/fake', to: 'fakes#index'
    get '/example', to: 'fakes#example'
    post '/example_post', to: 'fakes#example_post'

    get '*path', to: 'errors#error_404', via: :all
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  protected

  def confirmation_required?
    false
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Client < User
  include Elasticsearch::Model

  has_many :orders, dependent: :destroy
  has_many :mechanics, through: :orders

  def no_orders?
    orders.empty?
  end
end

Client.__elasticsearch__.create_index!

app/models/mechanic.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Mechanic < User
  include Elasticsearch::Model

  has_many :orders
  has_many :clients, through: :orders

  has_many :mechanic_services, dependent: :destroy
  has_many :services, through: :mechanic_services

  accepts_nested_attributes_for :mechanic_services

  validate :mechanic_services_cannot_be_blank?

  protected

  def mechanic_services_cannot_be_blank?
    errors.add(:mechanic_services, I18n.t('flashes.cannot_be_blank')) if mechanic_services.empty?
  end

  def confirmation_required?
    false
  end
end

Mechanic.__elasticsearch__.create_index!
Mechanic.import

app/models/mechanic_service.rb
# frozen_string_literal: true

class MechanicService < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/order.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Order < ApplicationRecord
  include Elasticsearch::Model

  include AASM
  aasm column: 'state', whiny_transitions: false do
    state :in_review, initial: true
    state :in_progress, :done

    event :progress do
      transitions from: :in_review, to: :in_progress, guard: :valid?
    end

    event :finish, guards: [:valid?] do
      transitions from: :in_progress, to: :done, guard: :valid?
    end
  end

  belongs_to :client
  belongs_to :mechanic

  has_one :service_order, dependent: :destroy
  has_one :service, through: :service_order

  accepts_nested_attributes_for :service_order, allow_destroy: true

  validates :state, inclusion: { in: %w[in_review in_progress done] }
  validate :description_cant_be_blank?

  validate :mechanic_can_do_service?

  def mechanic_can_do_service?
    errors.add(:services, I18n.t('flashes.One_of_the_services_is_not_supported_by_mechanic')) unless mechanic.services.include?(service_order.service)
  end

  def description_cant_be_blank?
    errors.add(:order, I18n.t('flashes.Blank_description')) if description.empty?
  end

  def done?
    state == 'done'
  end
end

Order.__elasticsearch__.create_index!
Order.import

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
end

app/models/service.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Service < ApplicationRecord
  include Elasticsearch::Model

  has_many :service_orders
  has_many :orders, through: :service_orders

  has_many :mechanic_services, dependent: :destroy
  has_many :mechanics, through: :mechanic_services

  validate :valid_price?
  validate :title_cannot_be_blank?
  validate :price_cant_be_zero?

  monetize :price_cents

  def valid_price?
    errors.add(:services, I18n.t('flashes.price_cant_be_negative_or_0')) if price <= 0
  end

  def title_cannot_be_blank?
    errors.add(:title, I18n.t('flashes.cannot_be_blank')) if title.empty?
  end

  def price_cant_be_zero?
    errors.add(:title, I18n.t('flashes.should_not_be_zero')) if price.zero?
  end
end

Service.__elasticsearch__.create_index!
Service.import

app/models/service_order.rb
# frozen_string_literal: true

class ServiceOrder < ApplicationRecord
  belongs_to :service
  belongs_to :order
end

app/models/specialization.rb
# frozen_string_literal: true

class Specialization < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/teammate.rb
# frozen_string_literal: true

class Teammate < User
  def confirmation_required?
    false
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class User < ApplicationRecord
  include Elasticsearch::Model

  validates :password, confirmation: true
  validates :first_name, :last_name, :email,
            :phone_number, exclusion: { in: [''], message: 'must not be blank' }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def full_name
    "#{first_name} #{last_name}"
  end
end

User.__elasticsearch__.create_index!

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  def me
    @me = current_user
  end

  def show
    @clients_all = Client.all
  end

  private

  def client_params
    required_key = @client.is_a?(Admin) ? :admin : :client
    params.require(required_key).permit(:first_name, :last_name, :email, :phone_number)
  end
end

app/controllers/fakes_controller.rb
# frozen_string_literal: true

class FakesController < ApplicationController
  skip_before_action :requier_login

  def index; end

  def example
    flash[:notice] = t :hello_flash
  end

  def example_post
    redirect_to example_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :requier_login, only: %i[guest forget_password send_reset_password_instructions]

  def guest; end

  def show_mechanics
    @mechanics = Mechanic.all
  end

  def show_teammates
    @teammates = Teammate.all
  end

  def edit
    @user = find_user(params[:id])
  end

  def update
    @user = find_user(params[:id])
    @user.update(user_params)
    puts "new obj: #{@user.first_name} #{@user.last_name} #{@user.phone_number} #{@user.email}"
    redirect_to me_path, notice: 'updated successfully'
  end

  def destroy
    @user = find_user(params[:id])
    if current?(@user) || admin?(current_user)
      reset_session if current?(@user)
      @user.destroy
    end

    redirect_to root_path
  end

  def forget_password
  end

  def send_reset_password_instructions
    user = find_user_by_email(params[:email])
    user.send_reset_password_instructions
    redirect_to root_path, notification: "we sent instructions on #{params[:email]}"
  end

  private

  def find_user_by_email email
    user = User.find_by(email: email)
    raise ActiveRecord::RecordNotFound unless user
    user
  end

  def user_params
    required_key = @user.is_a?(Admin) ? :admin : :client
    params.require(required_key).permit(:first_name, :last_name, :email, :phone_number)
  end

  def current?(user)
    user == current_user
  end

  def admin?(user)
    user.is_a Admin
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/errors_helper.rb
# frozen_string_literal: true

module ErrorsHelper
end

app/helpers/fakes_helper.rb
# frozen_string_literal: true

module FakesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/clients/edit.html.erb
<main id="main">
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container">

        <div class="section-title">
          <h2>Edit</h2>
        </div>

        <div class="row">

          <div class="col-lg-3"></div>

          <div class="col-lg-6 mt-4 mt-lg-0">

            <%= form_with url: client_path(@client), html: {class: "php-email-form"}, model: @client do |f| %>
              <div class="row">
                <div class="col-md-6 form-group">
                  <div class="form-floating">
                    <%= f.text_field :first_name, class: 'form-control', requiered: "requiered" %>
                    <label>Your first name</label>
                  </div>
                </div>

                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <div class="form-floating">
                    <%= f.text_field :last_name, class: 'form-control', requiered: "requiered" %>
                    <label>Your last name</label>
                  </div>         
                </div>     
              </div><br/>

              <div class="row">
                <div class="col-md-6 form-group">
                  <div class="form-floating">
                    <%= f.text_field :phone_number, class: 'form-control', requiered: "requiered" %>
                    <label>Your phone number</label>
                  </div>     
                </div>

                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <div class="form-floating">
                    <%= f.email_field :email, class: 'form-control', requiered: "requiered" %>
                    <label>Your email</label>
                  </div>     
                </div>     
              </div><br/>        

              <div class="text-center">
                <button type="submit">Update</button>
              </div>
            <% end %>

          </div>

        </div>

      </div>
<!-- End Contact Section -->  

app/views/clients/me.html.erb
<!-- ======= Team Section ======= -->
    <br/>
    <br/>
    <section id="team" class="team section-bg">
      <div class="container">

        <div class="section-title">
          <h2><%= t 'me.Profile' %></h2>
          <p><%= t 'me.Here_you_can_see_your_infomatiom' %></p>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch"></div>
            <!-- Profile info -->
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                <div class="member">
                    <div class="member-img">
                        <img src="assets/theme/img/team/team-1.jpg" class="img-fluid" alt="">
                    </div>

                    <div class="member-info">
                        <h4><%= @me.first_name %> <%= @me.last_name %></h4>
                        <span><%= @me.phone_number %></span>
                        <span><%= @me.email %></span>
                    </div>
                </div>
            </div>

        </div>

      </div>
    </section><!-- End Team Section -->

app/views/clients/show.html.erb
<!-- ======= Frequently Asked Questions Section ======= -->
<section id="faq" class="faq">
    <div class="container">

    <div class="section-title">
        <h2>Clients</h2>
    </div>

    <ul class="faq-list">

        <% @clients_all.each do |c| %>
            <li>

                <div data-bs-toggle="collapse" class="collapsed question" href=<%= "#faq#{c.id}" %>>
                    <%= "#{c.first_name} #{c.last_name} #{c.phone_number}" %>
                    <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i>
                </div>

                <div id=<%= "faq#{c.id}" %> class="collapse" data-bs-parent=".faq-list">
                    <section id="actual" class="why-us">
                        <div class="container">

                            <div class="row">
                                <% c.orders.each do |order|%>
                                <% @mechanic = Mechanic.find_by(id: order.mechanic_id) %>
                                    <div class="team col-lg-4">     
                                        <div class="col-lg-12">
                                            <div class="member">              
                                                <div class="member-img col-lg-12 mt-6 mt-lg-6">

                                                    <div class="box">
                                                        <span><%= order.state %></span>
                                                        <h4><%= order.description %></h4>
                                                        <p><%= "#{@mechanic.first_name} #{@mechanic.last_name}" %></p>
                                                        
                                                        <% if current_user.is_a?(Admin) && order.state != 'done' %>
                                                        <%= link_to 'Update state', client_order_path(c, order, state: 'change', locale: I18n.locale), method: :put, zclass: 'btn-get-started scrollto'%>
                                                        <% end %>
                                                    </div>                     

                                                    <% if order.in_review? %>
                                                    <div class="social">
                                                        <a href=<%= edit_client_order_path(current_user, order) %>>Edit</a>
                                                        <a href="">delet</a>
                                                    </div>
                                                    <% end %>

                                                </div>
                                            </div>
                                        </div>
                                    </div>  
                                <% end %> 
                            </div>

                        </div>
                    </section>
                </div>

            </li>
        <% end %>
        
    </ul>

    </div>
</section><!-- End Frequently Asked Questions Section -->