config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root '/en', controller: 'users', action: 'guest'
  scope ':locale', locale: /en|ru/ do
    devise_for :users, locale: I18n.locale

    resources :clients, only: %i[index show] do
      resources :orders
    end

    resources :users, only: %i[edit update destroy guest]

    get '/no_orders', to: 'users#no_orders'
    get '/show_mechanics', to: 'users#show_mechanics'
    get '/show_teammates', to: 'users#show_teammates'
    get '/forget_password', to: 'users#forget_password'
    get '/send_reset_password_instructions', to: 'users#send_reset_password_instructions'

    get '/guest', to: 'clients#guest'
    get '/me', to: 'clients#me'

    get '/show_services', to: 'orders#show_services'
    get '/show_actual_orders', to: 'orders#show_actual_orders'

    get '/fake', to: 'fakes#index'
    get '/example', to: 'fakes#example'
    post '/example_post', to: 'fakes#example_post'

    get '*path', to: 'errors#error_404', via: :all
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  protected

  def confirmation_required?
    false
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Client < User
  include Elasticsearch::Model

  has_many :orders, dependent: :destroy
  has_many :mechanics, through: :orders

  def no_orders?
    orders.empty?
  end
end

Client.__elasticsearch__.create_index!

app/models/mechanic.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Mechanic < User
  include Elasticsearch::Model

  has_many :orders
  has_many :clients, through: :orders

  has_many :mechanic_services, dependent: :destroy
  has_many :services, through: :mechanic_services

  accepts_nested_attributes_for :mechanic_services

  validate :mechanic_services_cannot_be_blank?

  protected

  def mechanic_services_cannot_be_blank?
    errors.add(:mechanic_services, I18n.t('flashes.cannot_be_blank')) if mechanic_services.empty?
  end

  def confirmation_required?
    false
  end
end

Mechanic.__elasticsearch__.create_index!
Mechanic.import

app/models/mechanic_service.rb
# frozen_string_literal: true

class MechanicService < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/order.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Order < ApplicationRecord
  include Elasticsearch::Model

  include AASM
  aasm column: 'state', whiny_transitions: false do
    state :in_review, initial: true
    state :in_progress, :done

    event :progress do
      transitions from: :in_review, to: :in_progress, guard: :valid?
    end

    event :finish, guards: [:valid?] do
      transitions from: :in_progress, to: :done, guard: :valid?
    end
  end

  belongs_to :client
  belongs_to :mechanic

  has_one :service_order, dependent: :destroy
  has_one :service, through: :service_order

  accepts_nested_attributes_for :service_order, allow_destroy: true

  validates :state, inclusion: { in: %w[in_review in_progress done] }
  validate :description_cant_be_blank?

  validate :mechanic_can_do_service?

  def mechanic_can_do_service?
    errors.add(:services, I18n.t('flashes.One_of_the_services_is_not_supported_by_mechanic')) unless mechanic.services.include?(service_order.service)
  end

  def description_cant_be_blank?
    errors.add(:order, I18n.t('flashes.Blank_description')) if description.empty?
  end

  def done?
    state == 'done'
  end
end

Order.__elasticsearch__.create_index!
Order.import

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
end

app/models/service.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Service < ApplicationRecord
  include Elasticsearch::Model

  has_many :service_orders
  has_many :orders, through: :service_orders

  has_many :mechanic_services, dependent: :destroy
  has_many :mechanics, through: :mechanic_services

  validate :valid_price?
  validate :title_cannot_be_blank?
  validate :price_cant_be_zero?

  monetize :price_cents

  def valid_price?
    errors.add(:services, I18n.t('flashes.price_cant_be_negative_or_0')) if price <= 0
  end

  def title_cannot_be_blank?
    errors.add(:title, I18n.t('flashes.cannot_be_blank')) if title.empty?
  end

  def price_cant_be_zero?
    errors.add(:title, I18n.t('flashes.should_not_be_zero')) if price.zero?
  end
end

Service.__elasticsearch__.create_index!
Service.import

app/models/service_order.rb
# frozen_string_literal: true

class ServiceOrder < ApplicationRecord
  belongs_to :service
  belongs_to :order
end

app/models/specialization.rb
# frozen_string_literal: true

class Specialization < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/teammate.rb
# frozen_string_literal: true

class Teammate < User
  def confirmation_required?
    false
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class User < ApplicationRecord
  include Elasticsearch::Model

  validates :password, confirmation: true
  validates :first_name, :last_name, :email,
            :phone_number, exclusion: { in: [''], message: 'must not be blank' }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def full_name
    "#{first_name} #{last_name}"
  end
end

User.__elasticsearch__.create_index!

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  def error_404
    @message = 'Page not found'
    render 'errors/not_found'
  end
end

app/controllers/fakes_controller.rb
# frozen_string_literal: true

class FakesController < ApplicationController
  skip_before_action :requier_login

  def index; end

  def example
    flash[:notice] = t :hello_flash
  end

  def example_post
    redirect_to example_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :requier_login, only: %i[guest forget_password send_reset_password_instructions]

  def guest; end

  def show_mechanics
    @mechanics = Mechanic.all
  end

  def show_teammates
    @teammates = Teammate.all
  end

  def edit
    @user = find_user(params[:id])
  end

  def update
    @user = find_user(params[:id])
    @user.update(user_params)
    puts "new obj: #{@user.first_name} #{@user.last_name} #{@user.phone_number} #{@user.email}"
    redirect_to me_path, notice: 'updated successfully'
  end

  def destroy
    @user = find_user(params[:id])
    if current?(@user) || admin?(current_user)
      reset_session if current?(@user)
      @user.destroy
    end

    redirect_to root_path
  end

  def forget_password
  end

  def send_reset_password_instructions
    user = find_user_by_email(params[:email])
    user.send_reset_password_instructions
    redirect_to root_path, notification: "we sent instructions on #{params[:email]}"
  end

  private

  def find_user_by_email email
    user = User.find_by(email: email)
    raise ActiveRecord::RecordNotFound unless user
    user
  end

  def user_params
    required_key = @user.is_a?(Admin) ? :admin : :client
    params.require(required_key).permit(:first_name, :last_name, :email, :phone_number)
  end

  def current?(user)
    user == current_user
  end

  def admin?(user)
    user.is_a Admin
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/errors_helper.rb
# frozen_string_literal: true

module ErrorsHelper
end

app/helpers/fakes_helper.rb
# frozen_string_literal: true

module FakesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/user/show.html.erb
<h1>info by id</h1>
<ul>
    <li><%=@user.first_name%></li>
    <li><%=@user.last_name%></li>
    <li><%=@user.email%></li>
    <li><%=@user.phone_number%></li>
</ul>
<%= link_to 'index',  user_index_path %>

app/views/users/edit.html.erb
<main id="main">
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container">

        <div class="section-title">
          <h2><%= t 'user_edit.Edit' %></h2>
        </div>

        <div class="row">

          <div class="col-lg-3"></div>

          <div class="col-lg-6 mt-4 mt-lg-0">

            <%= form_with url: user_path(@user), html: {class: "php-email-form"}, model: @user do |f| %>
              <div class="row">
                <div class="col-md-6 form-group">
                  <div class="form-floating">
                    <%= f.text_field :first_name, class: 'form-control', requiered: "requiered" %>
                    <label><%= t 'user_edit.Your_first_name' %></label>
                  </div>
                </div>

                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <div class="form-floating">
                    <%= f.text_field :last_name, class: 'form-control', requiered: "requiered" %>
                    <label><%= t 'user_edit.Your_last_name'%></label>
                  </div>         
                </div>     
              </div><br/>

              <div class="row">
                <div class="col-md-6 form-group">
                  <div class="form-floating">
                    <%= f.text_field :phone_number, class: 'form-control', requiered: "requiered" %>
                    <label><%= t 'user_edit.Your_phone_numbe' %></label>
                  </div>     
                </div>

                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <div class="form-floating">
                    <%= f.email_field :email, class: 'form-control', requiered: "requiered" %>
                    <label><%= t 'user_edit.Your_email' %></label>
                  </div>     
                </div>     
              </div><br/>        

              <div class="text-center">
                <button type="submit"><%= t 'user_edit.Update' %></button>
              </div>
            <% end %>

          </div>

        </div>

      </div>
    </section>
</main>
<!-- End Contact Section -->  

app/views/users/forget_password.html.erb
<main id="main">
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container">

        <div class="section-title">
          <h2>get reset password instructions</h2>
        </div>

        <div class="row">

          <div class="col-lg-3"></div>

          <div class="col-lg-6 mt-4 mt-lg-0">

            <%= form_with url: send_reset_password_instructions_path(), method: :get do |f| %>

              <div class="form-group mt-3">
                <div class="form-floating">                    
                  <%= f.email_field :email, id: 'email', class: 'form-control', row: '9', required: 'required' %>
                  <%= f.label 'Enter email to get instructions', for: 'email' %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit 'enter' %>
              </div>
            <% end %>

          </div>

        </div>

      </div>
    </section>
</main>
<!-- End Contact Section -->  

app/views/users/guest.html.erb
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row">
      <div class="col-lg-6 pt-2 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
        <h1><%= t 'guest.Greate_Solution_For_Your_Car' %></h1>
        <ul>
          <li><i class="ri-check-line"></i><%= t 'guest.Quick_service' %></li>
          <li><i class="ri-check-line"></i><%= t 'guest.Professional_work' %></li>
          <li><i class="ri-check-line"></i><%= t 'guest.Excellent_prices' %> </li>
        </ul>          
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img">
        <img src="assets/theme/img/hero-img.png" class="img-fluid" alt="">
      </div>
    </div>
  </div>

</section><!-- End Hero -->

<main id="main">
  <!-- ======= Counts Section ======= -->
  <section id="counts" class="counts section-bg">
    <div class="container">

      <div class="row">

        <div class="col-lg-4 col-md-6">
          <div class="count-box">
            <i class="bi bi-emoji-smile"></i>
            <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
            <p><%= t 'guest.Happy_Clients' %></p>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="bi bi-headset"></i>
            <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter"></span>
            <p><%= t 'guest.Hours_Of_Support' %></p>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="bi bi-people"></i>
            <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
            <p><%= t 'guest.Hard_Workers' %></p>
          </div>
        </div>

      </div>

    </div>
  </section><!-- End Counts Section -->

  <!-- ======= Services Section ======= -->
  <section id="services" class="services">
    <div class="container">

      <div class="section-title">
        <h2><%= t 'guest.Serivces' %></h2>
      </div>

      <div class="row">
        <div class="content col-xl-5 d-flex flex-column justify-content-center">
          <img src="assets/theme/img/services.png" class="img-fluid" alt="">
        </div>
        <div class="col-xl-7">
          <div class="icon-boxes d-flex flex-column justify-content-center">
            <div class="row">
              <div class="col-lg-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon-box iconbox-blue">
                  <div class="icon">
                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                      <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,521.0016835830174C376.1290562159157,517.8887921683347,466.0731472004068,529.7835943286574,510.70327084640275,468.03025145048787C554.3714126377745,407.6079735673963,508.03601936045806,328.9844924480964,491.2728898941984,256.3432110539036C474.5976632858925,184.082847569629,479.9380746630129,96.60480741107993,416.23090153303,58.64404602377083C348.86323505073057,18.502131276798302,261.93793281208167,40.57373210992963,193.5410806939664,78.93577620505333C130.42746243093433,114.334589627462,98.30271207620316,179.96522072025542,76.75703585869454,249.04625023123273C51.97151888228291,328.5150500222984,13.704378332031375,421.85034740162234,66.52175969318436,486.19268352777647C119.04800174914682,550.1803526380478,217.28368757567262,524.383925680826,300,521.0016835830174"></path>
                    </svg>
                    <i class="bx bxl-dribbble"></i>
                  </div>
                  <h4><a href=""><%= t 'guest.rubber_replacement' %></a></h4>
                </div>
              </div>

              <div class="col-lg-6 d-flex align-items-stretch mt-4 mt-lg-0" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon-box iconbox-orange ">
                  <div class="icon">
                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                      <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,582.0697525312426C382.5290701553225,586.8405444964366,449.9789794690241,525.3245884688669,502.5850820975895,461.55621195738473C556.606425686781,396.0723002908107,615.8543463187945,314.28637112970534,586.6730223649479,234.56875336149918C558.9533121215079,158.8439757836574,454.9685369536778,164.00468322053177,381.49747125262974,130.76875717737553C312.15926192815925,99.40240125094834,248.97055460311594,18.661163978235184,179.8680185752513,50.54337015887873C110.5421016452524,82.52863877960104,119.82277516462835,180.83849132639028,109.12597500060166,256.43424936330496C100.08760227029461,320.3096726198365,92.17705696193138,384.0621239912766,124.79988738764834,439.7174275375508C164.83382741302287,508.01625554203684,220.96474134820875,577.5009287672846,300,582.0697525312426"></path>
                    </svg>
                    <i class="bx bx-file"></i>
                  </div>
                  <h4><a href=""><%= t 'guest.technical_inspectation' %></a></h4>                    
                </div>
              </div>

              <div class="col-lg-6 d-flex align-items-stretch mt-4" data-aos="zoom-in" data-aos-delay="300">
                <div class="icon-box iconbox-pink">
                  <div class="icon">
                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                      <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,541.5067337569781C382.14930387511276,545.0595476570109,479.8736841581634,548.3450877840088,526.4010558755058,480.5488172755941C571.5218469581645,414.80211281144784,517.5187510058486,332.0715597781072,496.52539010469104,255.14436215662573C477.37192572678356,184.95920475031193,473.57363656557914,105.61284051026155,413.0603344069578,65.22779650032875C343.27470386102294,18.654635553484475,251.2091493199835,5.337323636656869,175.0934190732945,40.62881213300186C97.87086631185822,76.43348514350839,51.98124368387456,156.15599469081315,36.44837278890362,239.84606092416172C21.716077023791087,319.22268207091537,43.775223500013084,401.1760424656574,96.891909868211,461.97329694683043C147.22146801428983,519.5804099606455,223.5754009179313,538.201503339737,300,541.5067337569781"></path>
                    </svg>
                    <i class="bx bx-tachometer"></i>
                  </div>
                  <h4><a href=""><%= t 'guest.replacement_of_parts' %></a></h4>                    
                </div>
              </div>

              <div class="col-lg-6 d-flex align-items-stretch mt-4" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon-box iconbox-teal">
                  <div class="icon">
                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                      <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,503.46388370962813C374.79870501325706,506.71871716319447,464.8034551963731,527.1746412648533,510.4981551193396,467.86667711651364C555.9287308511215,408.9015244558933,512.6030010748507,327.5744911775523,490.211057578863,256.5855673507754C471.097692560561,195.9906835881958,447.69079081568157,138.11976852964426,395.19560036434837,102.3242989838813C329.3053358748298,57.3949838291264,248.02791733380457,8.279543830951368,175.87071277845988,42.242879143198664C103.41431057327972,76.34704239035025,93.79494320519305,170.9812938413882,81.28167332365135,250.07896920659033C70.17666984294237,320.27484674793965,64.84698225790005,396.69656628748305,111.28512138212992,450.4950937839243C156.20124167950087,502.5303643271138,231.32542653798444,500.4755392045468,300,503.46388370962813"></path>
                    </svg>
                    <i class="bx bx-layer"></i>
                  </div>
                  <h4><a href=""><%= t 'guest.renovation_work' %></a></h4>
                </div>
              </div>
            </div>
          </div><!-- End .content-->
        </div>
      </div>

    </div>
  </section><!-- End Services Section -->    

  <!-- ======= Frequently Asked Questions Section ======= -->
  <section id="faq" class="faq">
    <div class="container">

      <div class="section-title">
        <h2><%= t 'guest.frequently_asked_questions' %></h2>
      </div>

      <ul class="faq-list">

        <li>
          <div data-bs-toggle="collapse" class="collapsed question" href="#faq1"><%= t 'guest.how_long_does_it_take_to_serice' %><i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
          <div id="faq1" class="collapse" data-bs-parent=".faq-list">
            <p>
              <%= t 'guest.each_order_has_its_own_lead_time_but_our_masters_will_complete_everything_as_soon_as_possible' %>
            </p>
          </div>
        </li>

        <li>
          <div data-bs-toggle="collapse" href="#faq2" class="collapsed question"><%= t 'guest.what_is_your_work_schedule' %><i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
          <div id="faq2" class="collapse" data-bs-parent=".faq-list">
            <p>
              <%= t 'guest.we_work_every_day_from_800_to_1600_oclock' %>
            </p>
          </div>
        </li>

      </ul>

    </div>
  </section><!-- End Frequently Asked Questions Section -->
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer">

  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 footer-contact">
          <h3><%= t 'guest.carservice' %></h3>
          <p>
            <%= t 'guest.a108_adam_street' %><br>
            <%= t 'guest.new_york_ny_535022' %><br>
            <%= t 'guest.united_states' %><br><br>
            <strong><%= t 'guest.phone' %></strong><%= t 'guest.phone1_5589_55488_55' %><br>
            <strong><%= t 'guest.email' %></strong><%= t 'guest.carserviceror_gmail_com' %><br>
          </p>
        </div>

        <div class="col-lg-2 col-md-6 footer-links">          
          <h4><%= t 'guest.useful_links' %></h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <%= link_to t('guest.home'), root_path %>
            <li><i class="bx bx-chevron-right"></i> <%= link_to t('guest.team'), show_teammates_path %></li>
            <li><i class="bx bx-chevron-right"></i> <%= link_to t('guest.services'), show_services_path %> </a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

app/views/users/index.html.erb
<p>TestPage</p>

<div id="arr">
  <%= render partial: 'element', collection: @elements %>
</div>

<div id='search'>
  <%= form_with url: find_path, local: false, model: @text do |form| %>
    <%= form.text_field :text %>
    <%= form.submit 'search', id: 'search_btn' %>
  <% end %>
</div>

<script>
  $('#text').on("input", () => 
  {
    console.log('in')
    $('#search_btn').click()
  })
</script>

app/views/users/show.html.erb
<div id="arr">
  <% @elements.each do |el| %>
    <p><%= el %></p>
  <% end %>
</div>

app/views/users/show_mechanics.html.erb
<main id="main">
  <section id="team" class="team section-bg">
    <div class="container">

      <div class="section-title">
        <h2><%= t 'show_mechanics.Mechanics' %></h2>
        <p><%= t 'show_mechanics.Here_you_can_see_our_mechanics' %></p>
      </div>

      <div class="row">
        <% @mechanics.each_with_index do |m, i| %>
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <div class="member-img">
                <img src="/assets/theme/img/team/team-1.jpg" class="img-fluid" alt="">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4> <%= i+1 %>. <%= m.first_name %> <%= m.last_name %></h4>
                <ul>
                  <% m.services.each do |s| %>
                    <li> <%= s.title %> </li>
                  <% end %>
                <ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </section><!-- End Team Section -->
</main>
<!-- End Contact Section -->  

app/views/users/show_teamates.html.erb
<!-- ======= Team Section ======= -->
<section id="team" class="team section-bg">
  <div class="container">

    <div class="section-title">
      <h2>Team</h2>
      <p>Here you can see the leaders of our company. Each of them is a real professional in their field.</p>
    </div>

    <div class="row">
    <% Teammate.all.each_with_index do |t, i| %>
      <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
        <div class="member">
          <div class="member-img">
            <img src="/assets/theme/img/team/team-1.jpg" class="img-fluid" alt="">
            <div class="social">
              <a href=""><i class="bi bi-twitter"></i></a>
              <a href=""><i class="bi bi-facebook"></i></a>
              <a href=""><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="member-info">
            <h4><%= t.full_name%></h4>
          </div>
          
        </div>
      </div>
    <% end %>
  </div>

  </div>
</section><!-- End Team Section -->

app/views/users/show_teammates.html.erb
<!-- ======= Team Section ======= -->
<section id="team" class="team section-bg">
  <div class="container">

    <div class="section-title">
      <h2><%= t 'show_teammates.Team' %></h2>
      <p><%= t 'show_teammates.Here_you_can_see_the_leaders_of_our_company_Each_of_them_is_a_real_professional_in_their_field' %></p>
    </div>

    <div class="row">
    <% Teammate.all.each_with_index do |t, i| %>
      <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
        <div class="member">
          <div class="member-img">
            <img src="/assets/theme/img/team/team-1.jpg" class="img-fluid" alt="">
            <div class="social">
              <a href=""><i class="bi bi-twitter"></i></a>
              <a href=""><i class="bi bi-facebook"></i></a>
              <a href=""><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="member-info">
            <h4><%= t.full_name%></h4>
          </div>
          
        </div>
      </div>
    <% end %>
  </div>

  </div>
</section><!-- End Team Section -->