config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root '/en', controller: 'users', action: 'guest'
  scope ':locale', locale: /en|ru/ do
    devise_for :users, locale: I18n.locale

    resources :clients, only: %i[index show] do
      resources :orders
    end

    resources :users, only: %i[edit update destroy guest]

    get '/no_orders', to: 'users#no_orders'
    get '/show_mechanics', to: 'users#show_mechanics'
    get '/show_teammates', to: 'users#show_teammates'
    get '/forget_password', to: 'users#forget_password'
    get '/send_reset_password_instructions', to: 'users#send_reset_password_instructions'

    get '/guest', to: 'clients#guest'
    get '/me', to: 'clients#me'

    get '/show_services', to: 'orders#show_services'
    get '/show_actual_orders', to: 'orders#show_actual_orders'

    get '/fake', to: 'fakes#index'
    get '/example', to: 'fakes#example'
    post '/example_post', to: 'fakes#example_post'

    get '*path', to: 'errors#error_404', via: :all
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  protected

  def confirmation_required?
    false
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Client < User
  include Elasticsearch::Model

  has_many :orders, dependent: :destroy
  has_many :mechanics, through: :orders

  def no_orders?
    orders.empty?
  end
end

Client.__elasticsearch__.create_index!

app/models/mechanic.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Mechanic < User
  include Elasticsearch::Model

  has_many :orders
  has_many :clients, through: :orders

  has_many :mechanic_services, dependent: :destroy
  has_many :services, through: :mechanic_services

  accepts_nested_attributes_for :mechanic_services

  validate :mechanic_services_cannot_be_blank?

  protected

  def mechanic_services_cannot_be_blank?
    errors.add(:mechanic_services, I18n.t('flashes.cannot_be_blank')) if mechanic_services.empty?
  end

  def confirmation_required?
    false
  end
end

Mechanic.__elasticsearch__.create_index!
Mechanic.import

app/models/mechanic_service.rb
# frozen_string_literal: true

class MechanicService < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/order.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Order < ApplicationRecord
  include Elasticsearch::Model

  include AASM
  aasm column: 'state', whiny_transitions: false do
    state :in_review, initial: true
    state :in_progress, :done

    event :progress do
      transitions from: :in_review, to: :in_progress, guard: :valid?
    end

    event :finish, guards: [:valid?] do
      transitions from: :in_progress, to: :done, guard: :valid?
    end
  end

  belongs_to :client
  belongs_to :mechanic

  has_one :service_order, dependent: :destroy
  has_one :service, through: :service_order

  accepts_nested_attributes_for :service_order, allow_destroy: true

  validates :state, inclusion: { in: %w[in_review in_progress done] }
  validate :description_cant_be_blank?

  validate :mechanic_can_do_service?

  def mechanic_can_do_service?
    errors.add(:services, I18n.t('flashes.One_of_the_services_is_not_supported_by_mechanic')) unless mechanic.services.include?(service_order.service)
  end

  def description_cant_be_blank?
    errors.add(:order, I18n.t('flashes.Blank_description')) if description.empty?
  end

  def done?
    state == 'done'
  end
end

Order.__elasticsearch__.create_index!
Order.import

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
end

app/models/service.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Service < ApplicationRecord
  include Elasticsearch::Model

  has_many :service_orders
  has_many :orders, through: :service_orders

  has_many :mechanic_services, dependent: :destroy
  has_many :mechanics, through: :mechanic_services

  validate :valid_price?
  validate :title_cannot_be_blank?
  validate :price_cant_be_zero?

  monetize :price_cents

  def valid_price?
    errors.add(:services, I18n.t('flashes.price_cant_be_negative_or_0')) if price <= 0
  end

  def title_cannot_be_blank?
    errors.add(:title, I18n.t('flashes.cannot_be_blank')) if title.empty?
  end

  def price_cant_be_zero?
    errors.add(:title, I18n.t('flashes.should_not_be_zero')) if price.zero?
  end
end

Service.__elasticsearch__.create_index!
Service.import

app/models/service_order.rb
# frozen_string_literal: true

class ServiceOrder < ApplicationRecord
  belongs_to :service
  belongs_to :order
end

app/models/specialization.rb
# frozen_string_literal: true

class Specialization < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/teammate.rb
# frozen_string_literal: true

class Teammate < User
  def confirmation_required?
    false
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class User < ApplicationRecord
  include Elasticsearch::Model

  validates :password, confirmation: true
  validates :first_name, :last_name, :email,
            :phone_number, exclusion: { in: [''], message: 'must not be blank' }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def full_name
    "#{first_name} #{last_name}"
  end
end

User.__elasticsearch__.create_index!

app/controllers/fakes_controller.rb
# frozen_string_literal: true

class FakesController < ApplicationController
  skip_before_action :requier_login

  def index; end

  def example
    flash[:notice] = t :hello_flash
  end

  def example_post
    redirect_to example_path
  end
end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    @service_orders = @user.service_orders
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @mechanics = Mechanic.all
    @services = Service.all
    @service_id = params[:service_id].to_i
    logger.info("!!!service_id: #{@service_id}; is_i?: #{@service_id.is_a? Integer}")
  end

  def show_actual_orders
    @orders = current_user.service_orders
    redirect_to users_path, notice: 'You have no orders yet' if @orders.empty?
  end

  def show_services
    @services = Service.all
  end

  def create
    current_user.service_orders.create(service_orders_params)
    Specialization.create(mechanic_id: service_orders_params[:mechanic_id], service_id: service_orders_params[:service_id])
    redirect_to users_path, notice: 'new order added'
  end

  def edit
    @user = User.find_by(id: params[:user_id])
    @order = ServiceOrder.find_by(id: params[:id])
  end

  def update
    @order = ServiceOrder.find_by(id: params[:id])

    if params[:state]
      case @order.state
      when 'accepted'
        @order.progress!
      when 'in_progress'
        @order.finish!
      end
    else
      @order.update(service_orders_params) unless params[:state]
    end

    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params[:user_id])

    puts "params_id: #{params[:user_id]}"

    ServiceOrder.find_by(id: params[:id]).destroy
    redirect_to user_service_orders_path(@user)
  end

  private

  def service_orders_params
    params.require(:service_order).permit(:description, :mechanic_id, :service_id)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/errors_helper.rb
# frozen_string_literal: true

module ErrorsHelper
end

app/helpers/fakes_helper.rb
# frozen_string_literal: true

module FakesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/service_orders/edit.html.erb
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
<link href='https://bootstraptema.ru/snippets/form/2017/recaptcha/custom.css' rel='stylesheet' type='text/css'>

 <div class="container">
    <div class="row">
        <div class="col-lg-3 col-lg-offset-4">
            <h1 class="text-center">Edit Order</h1>

            <%= form_with url: user_service_order_path(@user, @order), model: @order do |f| %>
                    <div class="messages"></div>

                    <div class="controls">
                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label>Description *</label>
                            <%=f.text_field :description, class: "form-control", placeholder: "Please enter your firstname *", required: "required", data_error: "Firstname is required."%>
                            <div class="help-block with-errors"></div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <input type="submit" class="btn btn-success btn-send" value="save">
                      </div>
                    </div>

                </div>
            <% end %>
        </div><!-- /.col-lg-8 col-lg-offset-2 -->
    </div> <!-- /.row-->
 </div> <!-- /.container-->

app/views/service_orders/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />

<style>
    [class*="sticker"] {
    position: relative;
    margin: 15px 0;
    padding: 33px 15px 15px;
    background: #fff;
    border-radius: 6px;
    box-shadow: 1px 1px 5px 2px rgba(0, 0, 0, .64)
    }
    [class*="sticker"]:after {
    content: attr(data-sticker);
    position: absolute;
    top: 0;
    padding: 3px 7px;
    font-size: 12px;
    font-weight: bold;
    background: #999;
    color: #fff
    }
    .sticker-left {
    border-top-left-radius: 6px
    }
    .sticker-right {
    border-top-right-radius: 6px
    }
    .sticker-left:after {
    left: 0;
    border-radius: 6px 0 6px 0
    }
    .sticker-right:after {
    right: 0;
    border-radius: 0 6px 0 6px
    }
    .sticker-danger:after {
    background: #d9534f
    }
    .sticker-warning:after {
    background: #f0ad4e
    }
    .sticker-success:after {
    background: #5cb85c
    }
    .sticker-info:after {
    background: #5bc0de
    }
    .sticker-inverse:after {
    background: #222
    }
    /* ----------------------------- */
    .btn{
    position: relative;
    color:#fff;
    border-radius:30px;
    text-transform: uppercase;
    transform: scale(1.1,1.1);
    transition:all 0.3s ease-out 0s;
    }
    .btn:hover{
    transform: scale(1,1);
    color:#fff;
    }
    .btn i{
    margin-right:15px;
    color:#fff;
    }
    .btn:before {
    content: "";
    position: absolute;
    bottom: -8px;
    left:0px;
    width:100%;
    height: 10px;
    filter: blur(20px);
    border-radius: 30px;
    display: inline-block;
    z-index: -1;
    transition: all 0.3s ease-out 0s;
    }
    .btn:hover:before{
    bottom:0;
    filter: blur(10px);
    }

    .btn.blue{
    background: linear-gradient(to left, #7474bf , #348ac7);
    }
    .btn.blue:before{
    background: linear-gradient(to right,#7474bf,#348ac7);
    }
    @media only screen and (max-width: 767px){
    .btn{
    margin-bottom:15px;
    }
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">            
            <div class="sticker-left" data-sticker="Information">
                <h1 class="text-center">service orders. now it is <%= "#{@service_orders.count}" %></h1>
                <div class="col-sm-2">                        
                    <%= link_to "index", users_path, class: "btn btn-sm blue" %>
                </div>

                <div class="col-sm-2">                        
                    <%= link_to 'add order', new_user_service_order_path(@user), class: "btn btn-sm blue" %>
                </div>
            </div>
            <br/>
            <% @service_orders.each do |order| %>
                  <div class="sticker-right sticker-info" data-sticker=<%= "#{ order.state }" %>>
                    <pre>
                        <%= "#{order.description}." %>
                    </pre>                    

                    <div class="col-sm-2">                            
                      <%= link_to 'edit', edit_user_service_order_path(@user, order), class: "btn btn-sm blue" %>
                    </div>

                    <div class="col-sm-2">                            
                      <%= link_to 'delete', user_service_order_path(@user, order), method: :delete, class: "btn btn-sm blue" %>
                    </div>

                    <% if current_user.is_a?(Admin) && !order.done? %>
                        <div class="col-sm-2">                            
                        <%= link_to 'update state', user_service_order_path(@user, order, state: 'update'), method: :put, class: "btn btn-sm blue" %>
                        </div>
                    <% end %>
                  </div>
                <br/>
            <% end %>
        </div>
    </div>
</div>

app/views/service_orders/new.html.erb
<main id="main">
  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact section-bg">
    <div class="container">

      <div class="section-title">
        <h2>Order</h2>
      </div>

      <div class="row">

        <div class="col-lg-3"></div>

        <div class="col-lg-6 mt-4 mt-lg-0">
          <%= form_with url: user_service_orders_path(current_user), html: {class: "php-email-form"}, model: current_user.service_orders.build do |f| %>
            <div class="row">
              <div class="form-group mt-3">

                <div class="form-floating">
                  <input type="text" id="description" name="service_order[description]" class="form-control" required>
                  <label for="description">Description</label>
                </div><br/>
                
                <!-- Mechanics select -->
                <div class="form-floating">
                  <select class="form-select" aria-label="Default select example"
                          name="service_order[mechanic_id]" id="mechanics">
                    <% @mechanics.each do |m| %>
                      <option value=<%= m.id %>>
                        <%= m.first_name %> <%= m.last_name %>
                      </option>
                    <% end %>
                  </select>
                  <label for="mechanics">Choose a mechanic</label>
                </div><br/>
                <!-- End Mechanics select -->
                
                <!-- Service select -->
                <div class="form-floating" >
                  <select name="service_order[service_id]" id="mechanics" class="form-select" aria-label="Default select example">
                    <% @services.each do |s| %>
                      <option value=<%= s.id %> <% if s.id == @service_id %> selected <% end %>>
                        <%= s.title %>: <%= s.price %>$
                      </option>
                    <% end %>
                  </select>
                  <label for="mechanics">Choose a service</label>
                </div>
                <!-- End Service select -->
              </div>     
            </div>
            <br/>              

            <div class="text-center">
              <button type="submit">Create</button>
            </div>
          <% end %>
        </div>

      </div>

    </div>
  </section>

  <section id="team" class="team section-bg">
    <div class="container">

      <div class="section-title">
        <h2>Mechanics</h2>
        <p>Here you can see our mechanics.</p>
      </div>

      <div class="row">
        <% @mechanics.each_with_index do |m, i| %>
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <div class="member-img">
                <img src="/assets/theme/img/team/team-1.jpg" class="img-fluid" alt="">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4> <%= i+1 %>. <%= m.first_name %> <%= m.last_name %></h4>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </section><!-- End Team Section -->
</main>
<!-- End Contact Section -->  

app/views/service_orders/show_actual_orders.html.erb
<section id="actual" class="why-us">
  <div class="container">

    <div class="row">

      <% @orders.each do |order|%>
        <div class="col-lg-4 mt-4 mt-lg-4">
            <div class="box">
            <span><%= order.id %></span>
            <h4><%= order.state %></h4>
            <p><%= order.description %></p>
            <% if current_user.is_a?(Admin) && order.state != 'done' %>
                <%= link_to 'Update state', user_service_order_path(current_user, order, state: 'change'), method: :put, zclass: 'btn-get-started scrollto'%>
            <% end %>
            </div>
        </div>
      <% end %> 

    </div>

  </div>
</section>