config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root '/en', controller: 'users', action: 'guest'
  scope ':locale', locale: /en|ru/ do
    devise_for :users, locale: I18n.locale

    resources :clients, only: %i[index show] do
      resources :orders
    end

    resources :users, only: %i[edit update destroy guest]

    get '/no_orders', to: 'users#no_orders'
    get '/show_mechanics', to: 'users#show_mechanics'
    get '/show_teammates', to: 'users#show_teammates'
    get '/forget_password', to: 'users#forget_password'
    get '/send_reset_password_instructions', to: 'users#send_reset_password_instructions'

    get '/guest', to: 'clients#guest'
    get '/me', to: 'clients#me'

    get '/show_services', to: 'orders#show_services'
    get '/show_actual_orders', to: 'orders#show_actual_orders'

    get '/fake', to: 'fakes#index'
    get '/example', to: 'fakes#example'
    post '/example_post', to: 'fakes#example_post'

    get '*path', to: 'errors#error_404', via: :all
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  protected

  def confirmation_required?
    false
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Client < User
  include Elasticsearch::Model

  has_many :orders, dependent: :destroy
  has_many :mechanics, through: :orders

  def no_orders?
    orders.empty?
  end
end

Client.__elasticsearch__.create_index!

app/models/mechanic.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Mechanic < User
  include Elasticsearch::Model

  has_many :orders
  has_many :clients, through: :orders

  has_many :mechanic_services, dependent: :destroy
  has_many :services, through: :mechanic_services

  accepts_nested_attributes_for :mechanic_services

  validate :mechanic_services_cannot_be_blank?

  protected

  def mechanic_services_cannot_be_blank?
    errors.add(:mechanic_services, I18n.t('flashes.cannot_be_blank')) if mechanic_services.empty?
  end

  def confirmation_required?
    false
  end
end

Mechanic.__elasticsearch__.create_index!
Mechanic.import

app/models/mechanic_service.rb
# frozen_string_literal: true

class MechanicService < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/order.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Order < ApplicationRecord
  include Elasticsearch::Model

  include AASM
  aasm column: 'state', whiny_transitions: false do
    state :in_review, initial: true
    state :in_progress, :done

    event :progress do
      transitions from: :in_review, to: :in_progress, guard: :valid?
    end

    event :finish, guards: [:valid?] do
      transitions from: :in_progress, to: :done, guard: :valid?
    end
  end

  belongs_to :client
  belongs_to :mechanic

  has_one :service_order, dependent: :destroy
  has_one :service, through: :service_order

  accepts_nested_attributes_for :service_order, allow_destroy: true

  validates :state, inclusion: { in: %w[in_review in_progress done] }
  validate :description_cant_be_blank?

  validate :mechanic_can_do_service?

  def mechanic_can_do_service?
    errors.add(:services, I18n.t('flashes.One_of_the_services_is_not_supported_by_mechanic')) unless mechanic.services.include?(service_order.service)
  end

  def description_cant_be_blank?
    errors.add(:order, I18n.t('flashes.Blank_description')) if description.empty?
  end

  def done?
    state == 'done'
  end
end

Order.__elasticsearch__.create_index!
Order.import

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
end

app/models/service.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Service < ApplicationRecord
  include Elasticsearch::Model

  has_many :service_orders
  has_many :orders, through: :service_orders

  has_many :mechanic_services, dependent: :destroy
  has_many :mechanics, through: :mechanic_services

  validate :valid_price?
  validate :title_cannot_be_blank?
  validate :price_cant_be_zero?

  monetize :price_cents

  def valid_price?
    errors.add(:services, I18n.t('flashes.price_cant_be_negative_or_0')) if price <= 0
  end

  def title_cannot_be_blank?
    errors.add(:title, I18n.t('flashes.cannot_be_blank')) if title.empty?
  end

  def price_cant_be_zero?
    errors.add(:title, I18n.t('flashes.should_not_be_zero')) if price.zero?
  end
end

Service.__elasticsearch__.create_index!
Service.import

app/models/service_order.rb
# frozen_string_literal: true

class ServiceOrder < ApplicationRecord
  belongs_to :service
  belongs_to :order
end

app/models/specialization.rb
# frozen_string_literal: true

class Specialization < ApplicationRecord
  belongs_to :mechanic
  belongs_to :service
end

app/models/teammate.rb
# frozen_string_literal: true

class Teammate < User
  def confirmation_required?
    false
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class User < ApplicationRecord
  include Elasticsearch::Model

  validates :password, confirmation: true
  validates :first_name, :last_name, :email,
            :phone_number, exclusion: { in: [''], message: 'must not be blank' }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def full_name
    "#{first_name} #{last_name}"
  end
end

User.__elasticsearch__.create_index!

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/errors_helper.rb
# frozen_string_literal: true

module ErrorsHelper
end

app/helpers/fakes_helper.rb
# frozen_string_literal: true

module FakesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CarService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Resi Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/assets/theme/img/favicon.png" rel="icon">
    <link href="/assets/theme/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/assets/theme/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/assets/theme/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/assets/theme/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/assets/theme/css/style.css" rel="stylesheet">
  </head>

  <body>    
    <!-- Head -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center justify-content-between">

          <h1 class="logo"><a href=''><%= t 'header.carservice' %></a></h1>
          <nav id="navbar" class="navbar">
            <ul> 
              <li>
                <%= form_with url: search_path, local: false, model: @text do |form| %>

                  <div class="form-floating">         
                    <%= form.text_field :text, class: 'form-control', id: 'text', required: true %>
                    <%= form.label 'Search', for: 'text' %>

                    <%= form.submit 'Searh', id: 'search_button', hidden: true %>
                  </div>
                <% end %>  

                <div id='results' style='position: relative; z-index: 2;'>   
                </div>   
              </li>

              <!-- Switch locale -->
              <li><a class="nav-link scrollto" href=<%= url_for(locale: I18n.locale == :en ? :ru : :en) %>>switch locale</a></li>       

              <!-- Home -->
              <li><a class="nav-link scrollto active" href=<%= root_path(locale: I18n.locale) %>><%= t 'header.home' %></a> </li>

              <% if current_user %>

                <!-- Profile -->
                <li class="dropdown"><a><span><%= t 'header.Profile' %></span> <i class="bi bi-chevron-down"></i></a>
                  <ul>
                    <li><a href=<%= me_path %>><%= t 'header.Me' %></a></li>
                    <li><a href=<%= edit_user_path(current_user) %>><%= t 'header.Edit' %></a></li>
                  </ul>
                </li>

                <!-- Orders -->
                <% if current_user.is_a?(Client) %>       
                  <li class="dropdown"><a><span><%= t 'header.Orders' %></span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                      <li>
                        <%= link_to t('header.Actual'), show_actual_orders_path() %>
                      </li>
                      <li><%= link_to t('header.New'), new_client_order_path(current_user) %></li>
                    </ul>
                  </li>         
                <% end %>

                <!-- Services -->
                <li class="dropdown"><a href=''><span><%= t 'header.Services' %></span> <i class="bi bi-chevron-down"></i></a>
                  <ul>
                    <li><a href=<%= show_services_path() %>><%= t 'header.info' %></a></li>
                  </ul>
                </li>

                <!-- Temmates -->
                <li><a class="nav-link scrollto" href=<%= show_teammates_path() %>><%= t 'header.team' %></a></li>

                <!-- Mechanics -->
                <li><a class="nav-link scrollto" href=<%= show_mechanics_path() %>><%= t 'header.Mechanics' %></a></li>
                
                <% if current_user.is_a? Admin%>
                  <!-- Show all -->
                  <li><a class="nav-link scrollto" href=<%= client_path(current_user) %> ><%= t 'header.Show_all' %></a></li>
                <% end %>

                <!-- Signout -->
                <li><a class="nav-link scrollto" href=<%= destroy_user_session_path %> data-method='delete'><%= t 'header.Sign_out' %></a></li>          
              <% else %>
                <!-- Sign in -->
                <li><a class="nav-link scrollto active" href=<%= new_user_session_path %>><%= t 'header.sign_in' %></a> </li>

                <!-- Sign up -->
                <li><a class="nav-link scrollto active" href=<%= new_user_registration_path %>><%= t 'header.sign_up' %></a> </li>
              <% end %>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav><!-- .navbar -->

        </div>        

      <!-- flash notifications -->    
        <div class='flash-container' id='flash-container'>
          <% logger.info("flash => #{flash.keys}") %>
          <% flash.each do |type, msg| %>

            <% if type == 'errors' %>
              <% msg.each do |error| %>
                <div class='p-3 mb-2 bg-danger text-white' role='alert'>
                  <%= error %>
                </div>
              <% end %>
            <% else %>
              <div class='alert alert-primary' role='alert'>
                <%= msg %>
              </div>
            <% end %>
            
          <% end %>    
        </div>
      <!-- End flash notifications --> 


    </header>
    <!-- End head -->

    <div class='main-container' id='main-container'>
      <%= yield %>
    </div>

  </body>
</html>

<script>
  $('#text').on('input', () =>
  {
    $('#search_button').click()
  })
</script>